/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './node_modules/flowbite/**/*.js'
  ],
  // Safelist classes dynamically generated by template tags (inspections_ui.py)
  safelist: [
    'badge-pending',
    'badge-pending-final',
    'badge-approved',
    'badge-rejected',
    'badge-active',
    'badge-in-progress',
    'badge-count',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        // Headers - Roboto Condensed
        'heading': ['"Roboto Condensed"', 'Arial Narrow', 'sans-serif'],
        // Body copy - Roboto
        'body': ['Roboto', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        // Sans fallback
        'sans': ['Roboto', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Multicam Brand Colors
        brand: {
          50: '#f8f7f7',
          100: '#eeedec',
          200: '#e0dcd7',
          300: '#d2c6b6',
          400: '#bdab93',
          500: '#a88f71',
          600: '#8e7657',
          700: '#756148',
          800: '#594936',
          900: '#3f3427',
          950: '#28221b',
        },
        // Original Multicam palette for accents
        multicam: {
          sand: '#C4B396',
          olive: '#5C5844',
          brown: '#6B5C4A',
          green: '#4A5442',
          tan: '#D4C5A9',
        },
        // Orange accent (coral)
        accent: {
          50: '#FEF3EE',
          100: '#FCE4D8',
          200: '#F9C6AF',
          300: '#F5A07C',
          400: '#F07347',
          500: '#E84D1C',
          600: '#D93D12',
          700: '#B42E10',
          800: '#902614',
          900: '#742316',
        },
      },
    },
  },
  plugins: [
    require('flowbite/plugin')
  ],
}
