/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './node_modules/flowbite/**/*.js'
  ],
  // Safelist classes dynamically generated by template tags (inspections_ui.py)
  safelist: [
    'badge-pending',
    'badge-pending-final',
    'badge-approved',
    'badge-rejected',
    'badge-active',
    'badge-in-progress',
    'badge-count',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'heading': ['"Roboto Condensed"', 'Arial Narrow', 'sans-serif'],
        'body': ['Roboto', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'sans': ['Roboto', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Warm-gray scale — overrides Tailwind's cool gray everywhere
        gray: {
          50:  '#FAF9F7',
          100: '#F5F3EF',
          200: '#E8E4DE',
          300: '#D5CFC6',
          400: '#A8A196',
          500: '#857E73',
          600: '#6B6459',
          700: '#2A2520',
          800: '#1A1714',
          900: '#0F0D0B',
          950: '#080706',
        },
        // Warm white for card/panel surfaces (inputs stay pure #fff)
        'warm-white': '#FEFDFB',
        // Vibrant orange accent (#FF6000) — primary action color
        accent: {
          50:  '#FFF4ED',
          100: '#FFE4CC',
          200: '#FFC999',
          300: '#FFA366',
          400: '#FF8133',
          500: '#FF6000',
          600: '#E65600',
          700: '#BF4800',
          800: '#993900',
          900: '#732B00',
        },
        // Multicam camo tones — used very sparingly for brand texture
        camo: {
          olive: '#5C5844',
          green: '#4A5442',
          sand:  '#C4B396',
          tan:   '#D4C5A9',
          brown: '#6B5C4A',
        },
        // Legacy brand scale (kept for backward compat, rarely used)
        brand: {
          50: '#f8f7f7', 100: '#eeedec', 200: '#e0dcd7', 300: '#d2c6b6',
          400: '#bdab93', 500: '#a88f71', 600: '#8e7657', 700: '#756148',
          800: '#594936', 900: '#3f3427', 950: '#28221b',
        },
      },
    },
  },
  plugins: [
    require('flowbite/plugin')
  ],
}
