# Generated by Django 5.2.8 on 2025-11-27 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamouflageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camouflage_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('environment', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('development', 'In Development')], default='active', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camouflage Type',
                'verbose_name_plural': 'Camouflage Types',
                'ordering': ['sort_order', 'camouflage_name'],
            },
        ),
        migrations.CreateModel(
            name='PrinterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, unique=True)),
                ('level_description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('requirements', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Printer Level',
                'verbose_name_plural': 'Printer Levels',
                'ordering': ['sort_order', 'level_name'],
            },
        ),
        migrations.CreateModel(
            name='CamouflageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf_word', 'PDF/Word Document'), ('ai', 'AI/Vector File'), ('image', 'Image File')], max_length=20)),
                ('file', models.FileField(upload_to='camouflage/%Y/%m/')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_camouflage_files', to=settings.AUTH_USER_MODEL)),
                ('camouflage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.camouflagetype')),
            ],
            options={
                'verbose_name': 'Camouflage File',
                'verbose_name_plural': 'Camouflage Files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('related_to_model', models.CharField(blank=True, max_length=50)),
                ('related_to_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'ordering': ['-upload_date'],
            },
        ),
    ]
