# Generated by Django 5.2.8 on 2025-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='related_to_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
