# Generated by Django 5.2.8 on 2025-11-27 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_admin_role_and_permissions'),
        ('core', '0002_change_related_to_id_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialArticle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Fabric/material name', max_length=255)),
                ('product_code', models.CharField(blank=True, help_text='Supplier product code', max_length=100)),
                ('composition', models.CharField(help_text='Fiber content (e.g., 50% Nylon, 50% Cotton)', max_length=255)),
                ('construction', models.CharField(choices=[('woven', 'Woven'), ('knit', 'Knit'), ('nonwoven', 'Non-Woven')], max_length=20)),
                ('weight_group', models.CharField(choices=[('light', 'Light (<4 oz/yd²)'), ('medium', 'Medium (4-8 oz/yd²)'), ('heavy', 'Heavy (>8 oz/yd²)')], max_length=20)),
                ('weight_value', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in oz/yd²', max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches', max_digits=6, null=True)),
                ('finish', models.CharField(blank=True, help_text='Finish type', max_length=255)),
                ('color', models.CharField(blank=True, default='Greige', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_camouflages', models.ManyToManyField(blank=True, help_text='Camouflage types this material is approved for', related_name='approved_articles', to='core.camouflagetype')),
                ('supplier', models.ForeignKey(limit_choices_to={'user_functionality': 'rm_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_articles', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Raw Material Article',
                'verbose_name_plural': 'Raw Material Articles',
                'ordering': ['supplier', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tds/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_documents', to='core.rawmaterialarticle')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Data Sheet',
                'verbose_name_plural': 'Technical Data Sheets',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmaterialarticle',
            index=models.Index(fields=['supplier'], name='core_rawmat_supplie_ca282a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialarticle',
            index=models.Index(fields=['construction', 'weight_group'], name='core_rawmat_constru_bf1404_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialarticle',
            index=models.Index(fields=['status'], name='core_rawmat_status_e06f0f_idx'),
        ),
    ]
