# Generated by Django 5.2.8 on 2025-11-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_admin_role_and_permissions'),
        ('core', '0003_add_raw_material_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('rm_supplier_name', models.CharField(blank=True, help_text='If RM supplier not in system', max_length=255)),
                ('fabric_type', models.CharField(max_length=255)),
                ('number_of_pieces', models.IntegerField(help_text='Number of marketing pieces needed')),
                ('yardage_to_be_used', models.DecimalField(blank=True, decimal_places=2, help_text='Expected yardage to be used (optional)', max_digits=10, null=True)),
                ('shipping_name', models.CharField(max_length=255)),
                ('shipping_street', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camouflage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_orders', to='core.camouflagetype')),
                ('fp_supplier', models.ForeignKey(limit_choices_to={'user_functionality': 'fp_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_orders', to='accounts.userprofile')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_marketing_orders', to=settings.AUTH_USER_MODEL)),
                ('rm_supplier', models.ForeignKey(blank=True, limit_choices_to={'user_functionality': 'rm_supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_orders_for', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Marketing Order',
                'verbose_name_plural': 'Marketing Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fp_supplier'], name='core_market_fp_supp_e8fb6a_idx'), models.Index(fields=['status'], name='core_market_status_84090d_idx')],
            },
        ),
    ]
