# Generated by Django 5.2.8 on 2025-12-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_marketing_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Color position (1-7). Determines display order.')),
                ('color_name', models.CharField(help_text='Color name with code (e.g., "Cream 524")', max_length=50)),
                ('camouflage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.camouflagetype')),
            ],
            options={
                'verbose_name': 'Variant Color',
                'verbose_name_plural': 'Variant Colors',
                'ordering': ['camouflage_type', 'position'],
                'unique_together': {('camouflage_type', 'position')},
            },
        ),
    ]
