# Generated by Django 6.0 on 2026-02-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variantcolor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='partner_files/%Y/%m/')),
                ('category', models.CharField(choices=[('standard', 'Standard Only'), ('narrow', 'Narrow Only'), ('both', 'Both (Standard & Narrow)')], default='both', help_text='Which partner types can see this file', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_partner_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner File',
                'verbose_name_plural': 'Partner Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
