# Generated by Django 6.0 on 2026-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_partner_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfile',
            name='file_type',
            field=models.CharField(choices=[('quality_specs', 'Quality Specifications'), ('misc', 'Misc')], default='quality_specs', help_text='Section this file appears under', max_length=15),
        ),
    ]
