# Generated by Django 5.2.8 on 2025-11-27 07:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('technical_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('technical_contact', models.CharField(blank=True, max_length=255)),
                ('commercial_email', models.EmailField(blank=True, max_length=254)),
                ('commercial_contact', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('user_functionality', models.CharField(choices=[('printer', 'Licensed Printer'), ('rm_supplier', 'Raw Material Supplier'), ('fp_supplier', 'Finished Product Supplier'), ('government', 'Government User'), ('admin', 'CP/Admin')], default='printer', max_length=20)),
                ('printer_type', models.CharField(blank=True, choices=[('standard', 'Standard Printer'), ('narrow_goods', 'Narrow Goods Specialist'), ('alternate', 'Alternate Account'), ('special', 'Special Account')], max_length=20)),
                ('license_agreement_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_agreement_docs', models.FileField(blank=True, null=True, upload_to='licenses/%Y/%m/')),
                ('google_sheet_fa_id', models.CharField(blank=True, max_length=255)),
                ('google_sheet_lot_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('test', 'Test Account')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mpp_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.printerlevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['user_functionality'], name='accounts_us_user_fu_70e643_idx'), models.Index(fields=['technical_email'], name='accounts_us_technic_31d75f_idx'), models.Index(fields=['company_name'], name='accounts_us_company_905f54_idx'), models.Index(fields=['status'], name='accounts_us_status_aa9625_idx')],
            },
        ),
    ]
