# Generated by Django 5.2.8 on 2025-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('inspector', 'Inspector (FA/Lot Review)'), ('accounting', 'Accounting'), ('reporting', 'Reporting'), ('full_admin', 'Full Admin')], default='', help_text='Only applicable for admin users', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_browse_rm_library',
            field=models.BooleanField(default=False, help_text='Can browse RM library'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Can manage user accounts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_order_marketing',
            field=models.BooleanField(default=False, help_text='Can order marketing materials'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_register_articles',
            field=models.BooleanField(default=False, help_text='Can register new RM articles'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_review_fa',
            field=models.BooleanField(default=False, help_text='Can review/approve FA submissions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_review_lots',
            field=models.BooleanField(default=False, help_text='Can review/approve Lot submissions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_submit_fa',
            field=models.BooleanField(default=False, help_text='Can submit First Articles'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_submit_lots',
            field=models.BooleanField(default=False, help_text='Can submit Lots'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_submit_reports',
            field=models.BooleanField(default=False, help_text='Can submit monthly reports'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_upload_tds',
            field=models.BooleanField(default=False, help_text='Can upload Technical Data Sheets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_printer_list',
            field=models.BooleanField(default=False, help_text='Can view printer list'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_functionality',
            field=models.CharField(choices=[('printer', 'Print Partner'), ('rm_supplier', 'Raw Material Supplier'), ('fp_supplier', 'Finished Product Supplier'), ('government', 'Government User'), ('admin', 'CP/Admin Staff')], default='printer', max_length=20),
        ),
    ]
