# Generated by Django 5.2.8 on 2025-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_admin_role_and_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='printer_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('narrow_goods', 'Narrow Goods Specialist'), ('alternate', 'Alternate Account'), ('special', 'Special Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('primary_inspector', 'Primary Inspector (FA First Review + Lots)'), ('final_inspector', 'Final Inspector (FA Final Review Only)'), ('staff_executive', 'Staff - Executive'), ('staff_finance', 'Staff - Finance'), ('staff_operations', 'Staff - Operations'), ('full_admin', 'Full Admin')], default='', help_text='Only applicable for admin users', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_functionality',
            field=models.CharField(choices=[('partner', 'Partner'), ('admin', 'Internal Staff')], default='partner', max_length=20),
        ),
    ]
