# Generated by Django 5.2.8 on 2025-12-21 00:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_printer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code for FA/Lot ID prefixes (e.g., ACME). Set once and do not change.', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full company name', max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Company',
                'verbose_name_plural': 'Partner Companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='accounts_pa_code_b155b3_idx'), models.Index(fields=['status'], name='accounts_pa_status_66f38c_idx')],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Partner company this user belongs to (for partners only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.partnercompany'),
        ),
    ]
