# Generated by Django 6.0 on 2026-02-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_partner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercompany',
            name='is_narrow',
            field=models.BooleanField(default=False, help_text='Company is approved for narrow goods'),
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Company is approved for standard goods'),
        ),
    ]
