# Generated by Django 6.0 on 2026-03-24 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_partner_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='technical_email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
