# Generated by Django 5.2.8 on 2025-11-27 07:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstArticleInspection',
            fields=[
                ('fai_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fsid', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('fabric_style', models.CharField(max_length=200)),
                ('shade_standard', models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta')], max_length=10)),
                ('shade_standard_number', models.CharField(blank=True, max_length=20)),
                ('spectral_reflectance_requirement', models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta')], max_length=20)),
                ('lot_number_identifier', models.CharField(max_length=50)),
                ('date_of_printing', models.DateField()),
                ('first_article_ship_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('name_of_printer_representative', models.CharField(max_length=50)),
                ('submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('sheet_name_generated', models.CharField(blank=True, max_length=250)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('pattern_execution', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50)),
                ('scale', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50)),
                ('spectral_reflectance', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50)),
                ('inspector_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_documents', models.ManyToManyField(blank=True, related_name='fa_inspections', to='core.fileupload')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_fas', to=settings.AUTH_USER_MODEL)),
                ('multicam_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fa_submissions', to='core.camouflagetype')),
                ('submission_documents', models.ManyToManyField(blank=True, related_name='fa_submissions', to='core.fileupload')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_submissions', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'First Article Inspection',
                'verbose_name_plural': 'First Article Inspections',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='LotAcceptance',
            fields=[
                ('lot_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fsid', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('fabric_style', models.CharField(max_length=200)),
                ('shade_standard', models.CharField(max_length=10)),
                ('shade_standard_number', models.CharField(blank=True, max_length=20)),
                ('spectral_reflectance_requirement', models.CharField(max_length=20)),
                ('original_first_article_lot_identifier', models.CharField(max_length=50)),
                ('lot_identifier', models.CharField(max_length=50)),
                ('number_of_yards_printed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_samples', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('individual_sample_numbers', models.TextField()),
                ('date_of_printing', models.DateField()),
                ('date_shipped', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('name_of_submitter', models.CharField(max_length=50)),
                ('submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('sheet_name_generated', models.CharField(blank=True, max_length=250)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('evaluation_type', models.CharField(choices=[('simple', '27-row form (2 samples)'), ('standard', '37-row form (3 samples)'), ('complex', '57-row form (6+ samples)')], default='standard', max_length=20)),
                ('pattern_execution', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50)),
                ('scale', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50)),
                ('spectral_reflectance', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50)),
                ('evaluation_scores', models.JSONField(blank=True, default=dict)),
                ('inspector_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_documents', models.ManyToManyField(blank=True, related_name='lot_inspections', to='core.fileupload')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_lots', to=settings.AUTH_USER_MODEL)),
                ('original_fa', models.ForeignKey(help_text='Must reference approved FA', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inspections.firstarticleinspection')),
                ('submission_documents', models.ManyToManyField(blank=True, related_name='lot_submissions', to='core.fileupload')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_submissions', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Lot Acceptance',
                'verbose_name_plural': 'Lot Acceptances',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AddIndex(
            model_name='firstarticleinspection',
            index=models.Index(fields=['status', 'submission_date'], name='inspections_status_72fb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='firstarticleinspection',
            index=models.Index(fields=['vendor', 'submission_date'], name='inspections_vendor__1ec0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='firstarticleinspection',
            index=models.Index(fields=['multicam_variant'], name='inspections_multica_f649a7_idx'),
        ),
        migrations.AddIndex(
            model_name='lotacceptance',
            index=models.Index(fields=['status', 'submission_date'], name='inspections_status_cbf46e_idx'),
        ),
        migrations.AddIndex(
            model_name='lotacceptance',
            index=models.Index(fields=['vendor', 'submission_date'], name='inspections_vendor__716e26_idx'),
        ),
        migrations.AddIndex(
            model_name='lotacceptance',
            index=models.Index(fields=['original_fa'], name='inspections_origina_c05223_idx'),
        ),
    ]
