# Generated by Django 5.2.8 on 2025-11-27 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_admin_role_and_permissions'),
        ('core', '0002_change_related_to_id_to_charfield'),
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(help_text='Date report was submitted')),
                ('period_from', models.DateField(help_text='Reporting period start date')),
                ('period_to', models.DateField(help_text='Reporting period end date')),
                ('billing_date', models.DateField()),
                ('billing_document_reference', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(help_text='Manufacturer/customer name', max_length=255)),
                ('customer_po', models.CharField(blank=True, help_text='Customer PO number', max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('material_number', models.CharField(blank=True, max_length=100)),
                ('fabric_type', models.CharField(help_text='Fabric/substrate description', max_length=200)),
                ('yardage_produced', models.DecimalField(decimal_places=2, help_text='Yardage produced', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cuttable_width', models.DecimalField(blank=True, decimal_places=2, help_text='Cuttable width in inches', max_digits=6, null=True)),
                ('mpg_reference', models.CharField(blank=True, help_text='Military/Government reference', max_length=100)),
                ('non_license_fee_printing', models.BooleanField(default=False, help_text='Check if this is non-license fee printing')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('invoiced', 'Invoiced')], default='submitted', max_length=20)),
                ('invoice_reference', models.CharField(blank=True, help_text='Added by accounting after invoice generated', max_length=100)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mc_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='core.camouflagetype')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='accounts.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['printer', 'report_date'], name='inspections_printer_991e9f_idx'), models.Index(fields=['status'], name='inspections_status_03e95d_idx'), models.Index(fields=['period_from', 'period_to'], name='inspections_period__3a89f4_idx')],
            },
        ),
    ]
