# Generated by Django 5.2.8 on 2025-12-12 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_printer_type_and_more'),
        ('core', '0004_add_marketing_order'),
        ('inspections', '0002_add_monthly_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlyreport',
            name='inspections_printer_991e9f_idx',
        ),
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='inspector_comments',
        ),
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='pattern_execution',
        ),
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='spectral_reflectance',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='printer',
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='final_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='final_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reviewed_fas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='final_pattern_execution',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='final_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='final_scale',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='final_spectral_reflectance',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='primary_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='primary_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_reviewed_fas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='primary_pattern_execution',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='primary_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='primary_scale',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='primary_spectral_reflectance',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='firstarticleinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Primary Review'), ('pending_final', 'Pending Final Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['partner', 'report_date'], name='inspections_partner_8950ef_idx'),
        ),
    ]
