# Generated by Django 5.2.8 on 2025-12-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_remove_monthlyreport_inspections_printer_991e9f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstarticleinspection',
            name='is_historic',
            field=models.BooleanField(default=False, help_text='Historic FAs are imported legacy data. Some fields may be N/A. Only admins can set this.'),
        ),
    ]
