# Generated by Django 5.2.8 on 2025-12-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_add_is_historic_to_fa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstarticleinspection',
            old_name='lot_number_identifier',
            new_name='fa_lot_number',
        ),
        migrations.RenameField(
            model_name='lotacceptance',
            old_name='lot_identifier',
            new_name='lot_lot_number',
        ),
        migrations.RenameField(
            model_name='lotacceptance',
            old_name='original_first_article_lot_identifier',
            new_name='original_fa_lot_number',
        ),
    ]
