# Generated by Django 5.2.8 on 2025-12-13 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variantcolor'),
        ('inspections', '0005_rename_lot_number_identifier_firstarticleinspection_fa_lot_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('primary', 'Primary Inspector (1947)'), ('final', 'Final Inspector (Crye)')], help_text='Which inspection stage this evaluation is for', max_length=10)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('pattern_execution', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pattern execution evaluation', max_length=10)),
                ('scale', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Scale evaluation', max_length=10)),
                ('spectral_reflectance', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Spectral reflectance evaluation (blank if Visible Spectrum Only)', max_length=10)),
                ('comments', models.TextField(blank=True, help_text='Overall comments for this evaluation')),
                ('is_submitted', models.BooleanField(default=False, help_text='True when inspector has submitted this evaluation')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inspections.firstarticleinspection')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fa_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FA Evaluation',
                'verbose_name_plural': 'FA Evaluations',
                'ordering': ['fa', 'stage'],
                'unique_together': {('fa', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='FAColorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('0', '0 - Off-Shade'), ('0-1', '0-1 - Off-Shade/Much'), ('1', '1 - Much'), ('1-2', '1-2 - Much/Considerable'), ('2', '2 - Considerable'), ('2-3', '2-3 - Considerable/Noticeable'), ('3', '3 - Noticeable'), ('3-4', '3-4 - Noticeable/Slight'), ('4', '4 - Slight'), ('4-5', '4-5 - Slight/Equal'), ('5', '5 - Equal')], help_text='Shade matching rating (>= 3 is Pass)', max_length=5)),
                ('comment', models.CharField(blank=True, help_text='Comment for this color evaluation', max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fa_evaluations', to='core.variantcolor')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_evaluations', to='inspections.faevaluation')),
            ],
            options={
                'verbose_name': 'FA Color Evaluation',
                'verbose_name_plural': 'FA Color Evaluations',
                'ordering': ['color__position'],
                'unique_together': {('evaluation', 'color')},
            },
        ),
    ]
