# Generated by Django 5.2.8 on 2025-12-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_add_evaluation_attempt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstarticleinspection',
            name='name_of_printer_representative',
        ),
        migrations.RemoveField(
            model_name='lotacceptance',
            name='name_of_submitter',
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='submitter_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='submitter_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lotacceptance',
            name='submitter_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lotacceptance',
            name='submitter_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
