# Generated by Django 5.2.8 on 2025-12-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_partner_company'),
        ('inspections', '0010_unique_lot_evaluation_per_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstarticleinspection',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Partner company that owns this FA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fa_submissions', to='accounts.partnercompany'),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='submitter_email',
            field=models.EmailField(blank=True, default='', help_text='Submitter email at time of submission (immutable)', max_length=254),
        ),
        migrations.AddField(
            model_name='firstarticleinspection',
            name='submitter_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='Original User ID at time of submission (immutable)', null=True),
        ),
        migrations.AddField(
            model_name='lotacceptance',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Partner company that owns this Lot', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_submissions', to='accounts.partnercompany'),
        ),
        migrations.AddField(
            model_name='lotacceptance',
            name='submitter_email',
            field=models.EmailField(blank=True, default='', help_text='Submitter email at time of submission (immutable)', max_length=254),
        ),
        migrations.AddField(
            model_name='lotacceptance',
            name='submitter_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='Original User ID at time of submission (immutable)', null=True),
        ),
        migrations.AlterField(
            model_name='firstarticleinspection',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fa_submissions', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='lotacceptance',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_submissions', to='accounts.userprofile'),
        ),
    ]
