# Generated by Django 6.0 on 2026-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_add_company_and_submitter_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstarticleinspection',
            name='is_bdcs',
            field=models.BooleanField(default=False, help_text='Check if this is a BDCS inspection. BDCS submissions skip primary review.', verbose_name='BDCS'),
        ),
        migrations.AlterField(
            model_name='firstarticleinspection',
            name='spectral_reflectance_requirement',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('swir', 'SWIR')], max_length=20),
        ),
    ]
