# Generated by Django 6.0 on 2026-02-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_add_bdcs_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='faevaluation',
            name='pattern_execution_comment',
            field=models.CharField(blank=True, help_text='Comment for pattern execution', max_length=500),
        ),
        migrations.AddField(
            model_name='faevaluation',
            name='scale_comment',
            field=models.CharField(blank=True, help_text='Comment for scale', max_length=500),
        ),
        migrations.AddField(
            model_name='faevaluation',
            name='spectral_reflectance_comment',
            field=models.CharField(blank=True, help_text='Comment for spectral reflectance', max_length=500),
        ),
        migrations.AddField(
            model_name='lotsampleevaluation',
            name='pattern_execution_comment',
            field=models.CharField(blank=True, help_text='Comment for pattern execution', max_length=500),
        ),
        migrations.AddField(
            model_name='lotsampleevaluation',
            name='scale_comment',
            field=models.CharField(blank=True, help_text='Comment for scale', max_length=500),
        ),
        migrations.AddField(
            model_name='lotsampleevaluation',
            name='spectral_reflectance_comment',
            field=models.CharField(blank=True, help_text='Comment for spectral reflectance', max_length=500),
        ),
    ]
