# Generated by Django 6.0 on 2026-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_add_criteria_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacceptance',
            name='lot_lot_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
