# Generated by Django 6.0 on 2026-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_lot_number_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstarticleinspection',
            name='spectral_reflectance_requirement',
            field=models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('swir', 'SWIR'), ('Visible Spectrum Only', 'Visible Spectrum Only')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lotacceptance',
            name='spectral_reflectance_requirement',
            field=models.CharField(max_length=30),
        ),
    ]
