# Generated by Django 5.2.8 on 2025-11-27 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamouflageApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_camouflages', to=settings.AUTH_USER_MODEL)),
                ('camouflage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='core.camouflagetype')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camouflage_approvals', to='accounts.userprofile')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='approval_documents', to='core.fileupload')),
            ],
            options={
                'verbose_name': 'Camouflage Approval',
                'verbose_name_plural': 'Camouflage Approvals',
                'indexes': [models.Index(fields=['printer', 'status'], name='approvals_c_printer_5af7a4_idx'), models.Index(fields=['camouflage_type'], name='approvals_c_camoufl_8ceef7_idx')],
                'unique_together': {('printer', 'camouflage_type')},
            },
        ),
    ]
