# Generated by Django 5.2.8 on 2025-12-14 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App')], max_length=20)),
                ('notification_type', models.CharField(choices=[('fa_submitted', 'First Article Submitted'), ('fa_pending_final', 'FA Pending Final Review'), ('fa_approved', 'First Article Approved'), ('fa_rejected', 'First Article Rejected'), ('lot_submitted', 'Lot Submitted'), ('lot_approved', 'Lot Approved'), ('lot_rejected', 'Lot Rejected'), ('report_submitted', 'Report Submitted'), ('system', 'System Notification')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'channel', 'status'], name='notificatio_recipie_a9e57f_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
